---
- name: Create the InfluxDB directory
  ansible.builtin.file:
    path: /media/pi/raspberry-pi/grafana
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Create the settings directory (/etc/grafana)
  ansible.builtin.file:
    path: /media/pi/raspberry-pi/grafana/etc_grafana
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Add the default configuration file - grafana.ini
  ansible.builtin.copy:
    src: grafana.ini
    dest: /media/pi/raspberry-pi/grafana/etc_grafana/grafana.ini
    owner: root
    group: root
    mode: '0644'

- name: Create the data directory (/var/lib/grafana)
  ansible.builtin.file:
    path: /media/pi/raspberry-pi/grafana/var_lib_grafana
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Pull the grafana/grafana:{{ grafana_version }} Docker image
  community.docker.docker_image:
    name: grafana/grafana:{{ grafana_version }}
    source: pull
    state: present
  notify: Restart Grafana

- name: Start Grafana
  community.docker.docker_container:
    name: grafana
    image: grafana/grafana:{{ grafana_version }}
    container_default_behavior: no_defaults
    state: started
    user: root
    groups: root
    network_mode: monitoring
    volumes:
      - "/media/pi/raspberry-pi/grafana/etc_grafana/grafana.ini:/etc/grafana/grafana.ini"
      - "/media/pi/raspberry-pi/grafana/var_lib_grafana:/var/lib/grafana"
    published_ports:
      - "3000:3000"
