---
- name: Create the InfluxDB directory
  ansible.builtin.file:
    path: /media/pi/raspberry-pi/grafana
    state: directory

- name: Create the settings directory (/etc/grafana)
  ansible.builtin.file:
    path: /media/pi/raspberry-pi/grafana/etc_grafana
    state: directory

- name: Add the default configuration file - grafana.ini
  ansible.builtin.template:
    src: grafana.ini.j2
    dest: /media/pi/raspberry-pi/grafana/etc_grafana/grafana.ini

- name: Create the data directory (/var/lib/grafana)
  ansible.builtin.file:
    path: /media/pi/raspberry-pi/grafana/var_lib_grafana
    state: directory

- name: Pull the grafana/grafana:{{ grafana_version }} Docker image
  community.docker.docker_image:
    name: grafana/grafana:{{ grafana_version }}
    source: pull
    state: present
  notify: Restart Grafana

- name: Start Grafana
  community.docker.docker_container:
    name: grafana
    image: grafana/grafana:{{ grafana_version }}
    container_default_behavior: no_defaults
    state: started
    user: root
    groups: root
    network_mode: monitoring
    volumes:
      - "/media/pi/raspberry-pi/grafana/etc_grafana/grafana.ini:/etc/grafana/grafana.ini"
      - "/media/pi/raspberry-pi/grafana/var_lib_grafana:/var/lib/grafana"
    published_ports:
      - "3000:3000"
