---
- name: Create the InfluxDB directory
  ansible.builtin.file:
    path: /media/pi/raspberry-pi/influxdb
    state: directory

- name: Create the settings directory (/etc/influxdb)
  ansible.builtin.file:
    path: /media/pi/raspberry-pi/influxdb/etc_influxdb
    state: directory

- name: Add the default configuration file - influxdb.conf
  ansible.builtin.template:
    src: influxdb.conf.j2
    dest: /media/pi/raspberry-pi/influxdb/etc_influxdb/influxdb.conf

- name: Create the data directory (/var/lib/influxdb)
  ansible.builtin.file:
    path: /media/pi/raspberry-pi/influxdb/var_lib_influxdb
    state: directory

- name: Pull the influxdb:{{ influxdb_version }} Docker image
  community.docker.docker_image:
    name: influxdb:{{ influxdb_version }}
    source: pull
    state: present
  notify: Restart InfluxDB

- name: Start InfluxDB
  community.docker.docker_container:
    name: influxdb
    image: influxdb:{{ influxdb_version }}
    container_default_behavior: no_defaults
    state: started
    network_mode: monitoring
    volumes:
      - "/media/pi/raspberry-pi/influxdb/etc_influxdb/influxdb.conf:/etc/influxdb/influxdb.conf"
      - "/media/pi/raspberry-pi/influxdb/var_lib_influxdb:/var/lib/influxdb"
    published_ports:
      - "8086:8086"
      - "8088:8088"
