---
all:
  children:
    metrics:
      hosts:
        raspberrypi-1:
          ansible_host: 192.168.1.100
      vars:
        influxdb_token: "{{ lookup('env', 'INFLUXDB_TOKEN') }}"
  vars:
    ansible_user: ubuntu

