---
- name: Run all playbooks
  hosts: all
  tags:
    - all
  roles:
    - setup
    - telegraf
    - influxdb
    - grafana

- name: Run setup
  hosts: all
  tags:
    - setup
  roles:
    - setup

- name: Setup Telegraf
  hosts: all
  tags:
    - telegraf
  roles:
    - telegraf

- name: Setup InfluxDB
  hosts: all
  tags:
    - influxdb
  roles:
    - influxdb

- name: Setup Grafana
  hosts: all
  tags:
    - grafana
  roles:
    - grafana
