---
- name: Restart InfluxDB
  community.docker.docker_container:
    name: influxdb
    image: influxdb:{{ influxdb_version }}
    container_default_behavior: no_defaults
    state: started
    network_mode: monitoring
    volumes:
      - "/media/pi/raspberry-pi/influxdb/etc_influxdb2/config.yml:/etc/influxdb2/config.yml"
      - "/media/pi/raspberry-pi/influxdb/var_lib_influxdb2:/var/lib/influxdb2"
    published_ports:
      - "8086:8086"
