---
- name: Restart InfluxDB
  community.docker.docker_container:
    name: influxdb
    image: influxdb:{{ influxdb_version }}
    container_default_behavior: no_defaults
    state: started
    network_mode: monitoring
    volumes:
      - "/media/pi/raspberry-pi/influxdb/etc_influxdb/influxdb.conf:/etc/influxdb/influxdb.conf"
      - "/media/pi/raspberry-pi/influxdb/var_lib_influxdb:/var/lib/influxdb"
    published_ports:
      - "8086:8086"
      - "8088:8088"

- name: Restart Grafana
  community.docker.docker_container:
    name: grafana
    image: grafana/grafana:{{ grafana_version }}
    container_default_behavior: no_defaults
    state: started
    user: root
    groups: root
    network_mode: monitoring
    volumes:
      - "/media/pi/raspberry-pi/grafana/etc_grafana/grafana.ini:/etc/grafana/grafana.ini"
      - "/media/pi/raspberry-pi/grafana/var_lib_grafana:/var/lib/grafana"
    published_ports:
      - "3000:3000"

- name: Restart Telegraf
  community.docker.docker_container:
    name: telegraf
    image: telegraf:{{ telegraf_version }}
    container_default_behavior: no_defaults
    state: started
    network_mode: monitoring
    volumes:
      - "/media/pi/raspberry-pi/telegraf/etc_telegraf/telegraf.conf:/etc/telegraf/telegraf.conf"
      - "/var/run/docker.sock:/var/run/docker.sock"
