
- name: Restart Grafana
  community.docker.docker_container:
    name: grafana
    image: grafana/grafana:{{ grafana_version }}
    container_default_behavior: no_defaults
    state: started
    user: root
    groups: root
    network_mode: monitoring
    memory: 128m
    cpus: .2
    volumes:
      - "/media/pi/raspberry-pi/grafana/etc_grafana/grafana.ini:/etc/grafana/grafana.ini"
      - "/media/pi/raspberry-pi/grafana/var_lib_grafana:/var/lib/grafana"
    published_ports:
      - "3000:3000"
