---
- name: Installing additional required packages
  ansible.builtin.apt:
    update_cache: true
    name:
      - python3
      - python3-pip
      - python3-docker

- name: Validate Docker is started
  ansible.builtin.service:
    name: 'docker'
    state: started

- name: Configure monitoring network
  community.docker.docker_network:
    name: monitoring

- name: Mount storage
  ansible.posix.mount:
    src: UUID=ae4d940e-021b-4921-b50e-7e852b717bb1
    path: /media/pi/raspberry-pi
    fstype: ext4
    opts: defaults,auto,users,rw,nofail
    state: mounted
