---
- name: Create the Telegraf directory
  ansible.builtin.file:
    path: /media/pi/raspberry-pi/telegraf
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Create the settings directory (/etc/telegraf)
  ansible.builtin.file:
    path: /media/pi/raspberry-pi/telegraf/etc_telegraf
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Add the default configuration file - telegraf.conf
  ansible.builtin.copy:
    src: telegraf.conf
    dest: /media/pi/raspberry-pi/telegraf/etc_telegraf/telegraf.conf
    owner: root
    group: root
    mode: '0644'

# Allows telegraf to gather metrics from the Docker engine
- name: Add the telegraf user to the docker group
  ansible.builtin.user:
    name: telegraf
    group: docker
  notify: Restart Telegraf

# Allows telegraf to gather GPU temperature
- name: Add the telegraf user to the video group
  ansible.builtin.user:
    name: telegraf
    group: video
  notify: Restart Telegraf

- name: Pull the telegraf:{{ telegraf_version }} Docker image
  community.docker.docker_image:
    name: telegraf:{{ telegraf_version }}
    source: pull
    state: present
  notify: Restart Telegraf

- name: Start Telegraf
  community.docker.docker_container:
    name: telegraf
    image: telegraf:{{ telegraf_version }}
    container_default_behavior: no_defaults
    state: started
    network_mode: monitoring
    volumes:
      - "/media/pi/raspberry-pi/telegraf/etc_telegraf/telegraf.conf:/etc/telegraf/telegraf.conf"
      - "/var/run/docker.sock:/var/run/docker.sock"
