---
- name: Create the Telegraf directory
  ansible.builtin.file:
    path: /media/pi/raspberry-pi/telegraf
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Create the settings directory (/etc/telegraf)
  ansible.builtin.file:
    path: /media/pi/raspberry-pi/telegraf/etc_telegraf
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Add the default configuration file - telegraf.conf
  ansible.builtin.template:
    src: telegraf.conf.j2
    dest: /media/pi/raspberry-pi/telegraf/etc_telegraf/telegraf.conf
    owner: root
    group: root
    mode: '0644'
  notify: Restart Telegraf

- name: Pull the telegraf:{{ telegraf_version }} Docker image
  community.docker.docker_image:
    name: telegraf:{{ telegraf_version }}
    source: pull
    state: present
  notify: Restart Telegraf

- name: Start Telegraf
  community.docker.docker_container:
    name: telegraf
    image: telegraf:{{ telegraf_version }}
    container_default_behavior: no_defaults
    state: started
    network_mode: monitoring
    memory: 128m
    cpus: .25
    volumes:
      - "/media/pi/raspberry-pi/telegraf/etc_telegraf/telegraf.conf:/etc/telegraf/telegraf.conf"
